name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
from litellm import Router
agent_router = Router(model_list=[
    {"model_name": "organization_agent", "litellm_params": {"model": "ollama/mistral"}},
    {"model_name": "finance_agent", "litellm_params": {"model": "ollama/codellama"}}
])sequenceDiagram
    Project Manager->>Director Agent: New Task Request
    Director Agent->>Workload Agent: Capacity Check
    Workload Agent->>Finance Agent: Budget Approval
    Finance Agent-->>Director Agent: Approval Status
    Director Agent->>Project Agent: Task Assignment

  # Sample transaction analyzer
def analyze_transaction(agent, transaction):
    return agent.query(
        f"CATEGORIZE: {transaction['description']} | AMOUNT: {transaction['amount']}"
    )
